# Site settings
title: OpenRocket Simulator
email: openrocket-devel@lists.sourceforge.net 
description: > # this means to ignore newlines until "baseurl:"
  OpenRocket is a free, fully featured model rocket simulator that allows you to
  design and simulate your rockets before actually building and flying them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openrocket.info" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  openrocket 
source: 'jekyll_src'
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
markdown: kramdown
